{
  try {
    final TestOne testOne=createTestNode(TestOne.class);
    final TestSix testSix=createTestNode(TestSix.class);
    SixOneOneToOne rel=null;
    assertNotNull(testOne);
    assertNotNull(testSix);
    try (final Tx tx=app.tx()){
      rel=app.create(testSix,testOne,SixOneOneToOne.class);
      tx.success();
    }
     assertNotNull(rel);
    try (final Tx tx=app.tx()){
      GraphObject searchRes=app.getNodeById(testSix.getUuid());
      assertNotNull(searchRes);
      tx.success();
    }
     try (final Tx tx=app.tx()){
      testSix.getRelationships().iterator().next().getRelationship().delete();
      tx.success();
    }
     try (final Tx tx=app.tx()){
      rel.getUuid();
      fail("Accessing a deleted relationship should thow an exception.");
      tx.success();
    }
 catch (    NotFoundException nfex) {
      assertNotNull(nfex.getMessage());
    }
  }
 catch (  FrameworkException ex) {
    logger.log(Level.SEVERE,ex.toString());
    fail("Unexpected exception");
  }
}
